### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by qmxyouwenhua** [dunzeng/FedAWARE#3]
曾博，您好。关于您论文中使用了动量去最大化Surrogate gradient diversity的部分，我有些疑问，希望能得到您的指导。本人很菜，想了解为啥使用动量而不是使用梯度，是要保护隐私吗，感觉如果有历史动量，隐私还是会泄露。还是说起加速收敛、减少震荡的作用啊（感觉这个在用梯度计算完梯度最大化，再动量也行啊）。期待您的回复，非常感谢

**Comment by dunzeng** [comment]
文章中采用动量是有两个目的： 
1. 兼容采样算法/部分客户端参与问题。文章中的梯度多样性最大方法需要每一轮都有一个对所有参与方的本地梯度的估计，所以需要用到历史动量来去估计那些当前没被采样的参与方。
2. 有加速收敛、稳定本地梯度抖动的作用。

这篇文章没有讨论隐私问题，所以没有关心动量是否泄漏隐私，相关隐私保护技术应该可以兼容文章中的算法。

**Comment by qmxyouwenhua** [comment]
好的，谢谢佬，我明白了！！！对我帮助很大，非常感谢，佬牛逼

**Comment by qmxyouwenhua** [comment]
好的，谢谢佬，我明白了！！！对我帮助很大，非常感谢，佬牛逼
